// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package mpt

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LeafNode struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeafNode) Reset()         { *m = LeafNode{} }
func (m *LeafNode) String() string { return proto.CompactTextString(m) }
func (*LeafNode) ProtoMessage()    {}
func (*LeafNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0670c1aa125f517e, []int{0}
}
func (m *LeafNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeafNode.Unmarshal(m, b)
}
func (m *LeafNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeafNode.Marshal(b, m, deterministic)
}
func (dst *LeafNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafNode.Merge(dst, src)
}
func (m *LeafNode) XXX_Size() int {
	return xxx_messageInfo_LeafNode.Size(m)
}
func (m *LeafNode) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafNode.DiscardUnknown(m)
}

var xxx_messageInfo_LeafNode proto.InternalMessageInfo

func (m *LeafNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *LeafNode) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ExtNode struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Node                 []byte   `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtNode) Reset()         { *m = ExtNode{} }
func (m *ExtNode) String() string { return proto.CompactTextString(m) }
func (*ExtNode) ProtoMessage()    {}
func (*ExtNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0670c1aa125f517e, []int{1}
}
func (m *ExtNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtNode.Unmarshal(m, b)
}
func (m *ExtNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtNode.Marshal(b, m, deterministic)
}
func (dst *ExtNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtNode.Merge(dst, src)
}
func (m *ExtNode) XXX_Size() int {
	return xxx_messageInfo_ExtNode.Size(m)
}
func (m *ExtNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtNode.DiscardUnknown(m)
}

var xxx_messageInfo_ExtNode proto.InternalMessageInfo

func (m *ExtNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ExtNode) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

type BranchNode struct {
	Children             [][]byte `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	Target               []byte   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchNode) Reset()         { *m = BranchNode{} }
func (m *BranchNode) String() string { return proto.CompactTextString(m) }
func (*BranchNode) ProtoMessage()    {}
func (*BranchNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_0670c1aa125f517e, []int{2}
}
func (m *BranchNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchNode.Unmarshal(m, b)
}
func (m *BranchNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchNode.Marshal(b, m, deterministic)
}
func (dst *BranchNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchNode.Merge(dst, src)
}
func (m *BranchNode) XXX_Size() int {
	return xxx_messageInfo_BranchNode.Size(m)
}
func (m *BranchNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchNode.DiscardUnknown(m)
}

var xxx_messageInfo_BranchNode proto.InternalMessageInfo

func (m *BranchNode) GetChildren() [][]byte {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *BranchNode) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func init() {
	proto.RegisterType((*LeafNode)(nil), "mpt.LeafNode")
	proto.RegisterType((*ExtNode)(nil), "mpt.ExtNode")
	proto.RegisterType((*BranchNode)(nil), "mpt.BranchNode")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_node_0670c1aa125f517e) }

var fileDescriptor_node_0670c1aa125f517e = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcb, 0x4f, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x28, 0x51, 0x32, 0xe2, 0xe2, 0xf0,
	0x49, 0x4d, 0x4c, 0xf3, 0xcb, 0x4f, 0x49, 0x15, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53,
	0x25, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x92, 0x3e, 0x17, 0xbb, 0x6b, 0x45, 0x09, 0x0e, 0x2d, 0x42,
	0x5c, 0x2c, 0x20, 0x3b, 0xa0, 0x3a, 0xc0, 0x6c, 0x25, 0x07, 0x2e, 0x2e, 0xa7, 0xa2, 0xc4, 0xbc,
	0xe4, 0x0c, 0xb0, 0x1e, 0x29, 0x2e, 0x8e, 0xe4, 0x8c, 0xcc, 0x9c, 0x94, 0xa2, 0xd4, 0x3c, 0x09,
	0x46, 0x05, 0x66, 0x0d, 0x9e, 0x20, 0x38, 0x5f, 0x48, 0x8c, 0x8b, 0xad, 0x24, 0xb1, 0x28, 0x3d,
	0xb5, 0x04, 0xaa, 0x1f, 0xca, 0x4b, 0x62, 0x03, 0x3b, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0x6c, 0x24, 0x66, 0xc0, 0x00, 0x00, 0x00,
}
